# Generated by Django 4.2.4 on 2023-08-24 23:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="start_data",
            new_name="start_date",
        ),
    ]
